### ISSUE TITLE
RSSI doesn't transmit in junxion mode

### ISSUE THREAD

**Issue by jreus** [sensestage/ssdn_python#20]
Currently doing some heavy work in junxion mode.. and I realize that the RSSI osc messages (/minibee/rssi/) are not sent in junxion mode. The RSSI data appears fine when I switch to the standard osc format.

**Comment by sensestage** [comment]
ah, yes. didn't realise the junxion mode was used so intensively.
Will add it there!

**Comment by sensestage** [comment]
fixed in 6106b381a73fef885387977f961a096f78d37dec
