### ISSUE TITLE
pyserial-sensestage.tar.gz should uncompress into its own folder

### ISSUE THREAD

**Issue by novadeviator** [sensestage/ssdn_python#21]
It's quite annoying to have pyserial-sensestage.tar.gz untar/unzip into its parent folder (ssdn_python) messing things up. it should create its own folder 'python-serial' when uncompressing.

**Comment by sensestage** [comment]
ah, ok. It does this in the installation script:
```
tar xzvf pyserial-sensestage.tar.gz -C pyserial
```
but not automatically.
