### ISSUE TITLE
Output up to down instead of down to up

### ISSUE THREAD

**Issue by LFSaw** [sensestage/ssdn_python#7]
currently, the most recent log entry in the "Output" tab of pydon is on top. This is very unusual and makes reading extremely difficult. I'd love to see this changed to having last output on the bottom.

**Comment by sensestage** [comment]
I had an issue with the textview with autoscrolling when putting the
latest at the bottom, so I took a quick and dirty solution.

I would love to see a patch to get this fixed.

**Comment by sensestage** [comment]
fixed in 36701cd370d20802c7bf7d059173e030362e0c8c
